include: package:lint/analysis_options.yaml

analyzer:
    strong-mode:
    implicit-cast: false
    implicit-dynamic: false

linter:
    rules:
    avoid_print: false
    no_rintimeType_toString: false
    prefer_const_contructors: false
    